### ISSUE TITLE
Benchmark against `level-read-stream`

### ISSUE THREAD

**Issue by vweevers** [Level/web-stream#1]
Should be interesting because both use the same `highWaterMark` logic.

**Comment by vweevers** [comment]
Quite a bit slower, at least in Node.js.

![stream 1645375953106](https://user-images.githubusercontent.com/3055345/154854570-7fdf53c8-9049-4698-84da-b532f7eb6fc4.png)

**Comment by oskarlh** [comment]
Looks like it's the other way around now, at least on my machine running Node 20 and Windows 10. Web stream benchmark finishes in 1.4s. Not web stream benchmark finishes in 1.8s

**Comment by vweevers** [comment]
@oskarlh Oh that's nice. I haven't kept up with Node.js changes on this front, I guess they made improvements :)
